"""F3（阶段7，登记册 §七）：SWARM_* 环境开关【冻结登记册】。

问题：113→206 个 SWARM_* 直读开关散布全仓（仅少数进 settings），每轮 E2E 跑的都是
"从未整体验证的配置组合"。本模块把全部已知开关登记成单一事实源：
  - 值 = 首次出现的 file:line（索引指针，语义看现场注释）；
  - 新增 SWARM_* 而不登记 → test_phase7_env_registry 定向测试红（冻结面有牙）；
  - 三份 profile（config/profiles/{dev,e2e,prod}.env）冻结高影响开关的推荐组合。
纯数据模块：不 import 业务代码，不产生副作用。
"""

# 206 个已知开关（2026-07-10 阶段7 冻结基线；按名排序）
REGISTERED_ENVS: dict[str, str] = {
    "SWARM_ADVERSARIAL_DIFF_CHARS": "brain/nodes/adversarial.py:69",
    # R53-1：Maven 坐标/版本解析（仓库联网）。0=关闭（单测默认关，见 test/conftest.py：
    # 绝不让测试依赖网络，也杜绝"网络好就绿"的假绿）；关闭后行为=解析不到即如实省略。
    "SWARM_MAVEN_LOOKUP": "brain/maven_registry.py:_lookup_enabled",
    # #31-P2b/2c：npm/go 依赖版本解析（registry/proxy 联网），与 SWARM_MAVEN_LOOKUP 同义栈中立
    # 铺开。0=关闭（单测默认关：绝不让测试依赖网络/假绿）；关闭后=解析不到即如实丢弃。
    "SWARM_NPM_LOOKUP": "brain/npm_registry.py:_lookup_enabled",
    "SWARM_NPM_LOOKUP_TIMEOUT_S": "brain/npm_registry.py:_HTTP_TIMEOUT_S",
    "SWARM_GO_LOOKUP": "brain/go_registry.py:_lookup_enabled",
    "SWARM_GO_LOOKUP_TIMEOUT_S": "brain/go_registry.py:_HTTP_TIMEOUT_S",
    # R55-1：思考阶段预算（秒）。云端 reasoning 模型在思维链里原地打转时，max_tokens/stall
    # 看门狗都拦不住，墙钟兜底要先烧满 25 分钟。超此预算且尚未吐出正文 → 就地关 thinking
    # 用同一模型重开流（无损，下游无感）。0=关闭。
    "SWARM_MODEL_BRAIN_REASONING_PHASE_BUDGET_S": "config/settings.py:brain_reasoning_phase_budget_s",
    # R63-T7：流式复读退化探测（正文/思维链 token 级复读 → abort 流 + capability 换挡）。
    # enabled=总闸（0=回退旧行为：只靠 900s 墙钟/迭代上限兜底）；window/repeats 粗旋钮，
    # 覆盖率/多样性成对阈值固化在 models/degeneration.py（防只调一半打破误杀/漏杀平衡）。
    "SWARM_MODEL_STREAM_DEGEN_ENABLED": "config/settings.py:stream_degen_enabled",
    "SWARM_MODEL_STREAM_DEGEN_WINDOW_CHARS": "config/settings.py:stream_degen_window_chars",
    "SWARM_MODEL_STREAM_DEGEN_WORD_REPEATS": "config/settings.py:stream_degen_word_repeats",
    "SWARM_MODEL_STREAM_DEGEN_SEG_REPEATS": "config/settings.py:stream_degen_seg_repeats",
    "SWARM_MAVEN_LOOKUP_TIMEOUT_S": "brain/maven_registry.py:_HTTP_TIMEOUT_S",
    "SWARM_ADVERSARIAL_MAX_ROUNDS": "brain/nodes/adversarial.py:51",
    "SWARM_ADVERSARIAL_REVIEW_TIMEOUT": "brain/nodes/adversarial.py:61",
    "SWARM_ADVERSARIAL_VERIFY": "brain/nodes/adversarial.py:44",
    "SWARM_ALLOW_EXTERNAL_PROJECT_PATH": "api/routers/project.py:56",
    "SWARM_ALLOW_LEGACY_API_KEY": "config/settings.py:882",
    "SWARM_ALLOW_MULTIPROCESS": "api/app.py:886",
    "SWARM_ALLOW_RANDOM_EMBED": "project/preprocess.py:1283",
    "SWARM_API_HOST": "api/app.py:1928",
    "SWARM_API_KEY": "api/auth.py:1",
    "SWARM_API_LOG_LEVEL": "api/app.py:1930",
    "SWARM_API_PORT": "api/app.py:1929",
    "SWARM_AUDIT_RETENTION_DAYS": "api/app.py:1248",
    "SWARM_AUTO_ACCEPT": "brain/nodes/__init__.py:2728",
    "SWARM_BASELINE_STRICT_GATE": "brain/gates.py:193",
    "SWARM_BOOTSTRAP_ADMIN_PASSWORD": "config/settings.py:855",
    "SWARM_BRAIN_JSON_MODE": "brain/nodes/__init__.py:203",
    "SWARM_BRAIN_OFFLINE": "models/router.py:_raise_if_brain_offline",  # R65D-T5 注入调试轮零云端闸（构造点 fail-closed）
    "SWARM_BREAKER_COOLDOWN_S": "models/breaker.py:18",
    "SWARM_BREAKER_THRESHOLD": "models/breaker.py:17",
    "SWARM_CASSETTE_RECORD_DIR": "models/cassette_record.py:_ENV_DIR",
    "SWARM_CASSETTE_REPLAY_DIR": "models/cassette_playback.py:_ENV_DIR",   # Task#12 LLM 回放门控
    "SWARM_CASSETTE_REPLAY_MISS": "models/cassette_playback.py:_ENV_MISS",  # 回放 miss 策略(默认 error)
    "SWARM_CHECKPOINT_TTL_DAYS": "infra/checkpoint_gc.py:16",
    "SWARM_CLOUD_PROVIDER_MAX_CONCURRENCY": "models/router.py:392",
    "SWARM_CODEGRAPH_BIN": "project/codegraph.py:41",
    "SWARM_CONTRACT_CONCURRENCY": "brain/planning_nodes.py:1419",
    "SWARM_CONTRACT_MAX_ATTEMPTS": "brain/planning_nodes.py:1420",
    "SWARM_CONTRACT_MISSING_RATIO": "brain/integration_review.py:138",
    "SWARM_CONTRACT_SKELETON_MAX_ATTEMPTS": "brain/planning_nodes.py:1434",
    "SWARM_CONTRACT_SKELETON_TIMEOUT": "brain/planning_nodes.py:1429",
    "SWARM_CONTRACT_STAGE_TIMEOUT": "brain/planning_nodes.py:1421",
    "SWARM_DB_": "config/settings.py:105",
    "SWARM_DB_CONNECT_TIMEOUT": "infra/db.py:95",
    "SWARM_DB_POOL_MAX": "infra/db.py:22",
    "SWARM_DB_POOL_MAX_LIFETIME": "infra/db.py:85",
    "SWARM_DB_POOL_MIN": "infra/db.py:21",
    "SWARM_DB_POOL_TIMEOUT": "infra/db.py:78",
    "SWARM_DB_POSTGRES_URI": "config/settings.py:113",
    "SWARM_DISPATCH_ROLL_FACTOR": "brain/nodes/dispatch.py:616",  # R65D-T6 滚动派发补位因子（0=关回旧批门闩）
    "SWARM_DOCS_PUBLIC": "api/auth.py:28",
    "SWARM_ENV": "config/settings.py:719",
    "SWARM_EXTRACT_MAX_ITEMS": "brain/requirements_extract.py:41",
    "SWARM_SUBTASK_MAX_DISPATCH_TOTAL": "brain/nodes/failure.py:_lifetime_cap",
    "SWARM_EXEC_SIG_FUSE": "brain/nodes/failure.py:_handle_failure_impl(#108 签名不收敛熔断开关)",
    "SWARM_EXEC_SIG_FUSE_K": "brain/nodes/failure.py:_handle_failure_impl(#108 签名连击熔断阈值,默认6)",
    "SWARM_REDISPATCH_SOFT_DROP": "brain/nodes/dispatch.py:_soft_drop_enabled(#109 软掉账兑现开关)",
    "SWARM_REDISPATCH_HARD_WINDOWS": "brain/nodes/dispatch.py:_redispatch_hard_windows(#109 软掉账硬阈值,默认24)",
    "SWARM_REPLAN_DETERMINISTIC_LAND": "brain/nodes/failure.py:_handle_failure_impl(#107 replan 确定性落地开关)",
    "SWARM_GITLAB_MR_ON_ACCEPT": "brain/nodes/__init__.py:4359",
    "SWARM_GITLAB_PROJECT_ID": "brain/l3_gitlab.py:27",
    "SWARM_GITLAB_PUSH_ENABLED": "brain/l3_gitlab.py:32",
    "SWARM_GITLAB_REF": "brain/l3_gitlab.py:151",
    "SWARM_GITLAB_TOKEN": "brain/l3_gitlab.py:26",
    "SWARM_GITLAB_TRIGGER_TOKEN": "brain/l3_gitlab.py:242",
    "SWARM_GITLAB_URL": "brain/l3_gitlab.py:25",
    "SWARM_HEALTH_OK__": "worker/sandbox.py:902",
    "SWARM_INSTANCE_ID": "worker/sandbox.py:74",
    "SWARM_INTERRUPT_TTL_NOTIFY_H": "brain/runner.py:1885",
    "SWARM_KB_": "api/routers/config.py:683",
    "SWARM_KB_CHUNK_OVERLAP": "api/routers/config.py:768",
    "SWARM_KB_CHUNK_SIZE": "api/routers/config.py:767",
    "SWARM_KB_EMBEDDING_MODEL": "api/routers/config.py:710",
    "SWARM_KB_EMBED_API_KEY": "api/routers/config.py:720",
    "SWARM_KB_EMBED_BASE_URL": "project/preprocess.py:1218",
    "SWARM_KB_EMBED_BATCH_SIZE": "api/routers/config.py:715",
    "SWARM_KB_EMBED_DIMENSION": "project/preprocess.py:627",
    "SWARM_KB_EMBED_FORMAT": "api/routers/config.py:712",
    "SWARM_KB_EMBED_REUSE_PROVIDER": "api/routers/config.py:713",
    "SWARM_KB_HYBRID_UNION_SCROLL_LIMIT": "config/settings.py:650(R65B-T3 真混合候选并集关键词臂池上限)",
    "SWARM_KB_LOG_RETENTION_DAYS": "api/app.py:1290",
    "SWARM_KB_MAX_PRIORITY_FILES": "api/routers/config.py:766",
    "SWARM_KB_PRIORITY_FILE_TOP_K": "api/routers/config.py:765",
    "SWARM_KB_PRUNE_TIMEOUT": "api/app.py:1302",
    "SWARM_KB_RERANKER_MODEL": "api/routers/config.py:727",
    "SWARM_KB_RERANK_API_KEY": "api/routers/config.py:737",
    "SWARM_KB_RERANK_FORMAT": "api/routers/config.py:729",
    "SWARM_KB_RERANK_REUSE_PROVIDER": "api/routers/config.py:730",
    "SWARM_KB_RERANK_SCORE_THRESHOLD": "api/routers/config.py:732",
    "SWARM_KB_RERANK_TOP_K": "api/routers/config.py:763",
    "SWARM_KB_RERANK_URL": "api/routers/config.py:725",
    "SWARM_KB_RETRIEVAL_TOP_K": "api/routers/config.py:762",
    "SWARM_KB_SEMANTIC_SCORE_THRESHOLD": "api/routers/config.py:764",
    "SWARM_LANGSMITH_API_KEY": "api/_shared.py:47",
    "SWARM_LANGSMITH_ENDPOINT": "api/_shared.py:49",
    "SWARM_LANGSMITH_PROJECT": "api/_shared.py:48",
    "SWARM_LANGSMITH_TRACING": "api/_shared.py:46",
    "SWARM_LEADER_HEARTBEAT_SEC": "api/app.py:1071",
    "SWARM_LEDGER_RESERVATION_TTL_S": "models/ledger.py:83",
    "SWARM_LOCK_RENEW_INTERVAL_SEC": "infra/redis_client.py:270",
    "SWARM_LOCK_RENEW_TRANSIENT_MAX": "infra/redis_client.py:76",
    "SWARM_MAX_ACTIVE_PROJECTS": "infra/redis_client.py:430",
    "SWARM_MAX_CONCURRENT_TASKS": "brain/scheduler.py:10",
    "SWARM_MAX_TASK_TOKENS_PER_MODULE": "config/settings.py:762",
    "SWARM_MAX_TASK_TOKENS_PER_PLANNED_FILE": "config/settings.py:830(R65B-T1 文件规模二级预算弹性)",
    "SWARM_MILESTONE_REPORTS_KEEP": "project/store.py:2086",
    "SWARM_MODEL_": "api/app.py:518",
    "SWARM_MODEL_BRAIN_FALLBACK": "api/_shared.py:30",
    "SWARM_MODEL_BRAIN_PRIMARY": "api/_shared.py:29",
    "SWARM_MODEL_BRAIN_TEMPERATURE": "api/_shared.py:34",
    "SWARM_MODEL_LOCAL_API_KEY": "api/_shared.py:25",
    "SWARM_MODEL_LOCAL_BASE_URL": "api/_shared.py:28",
    "SWARM_MODEL_MODEL_PROVIDERS": "api/routers/config.py:505",
    "SWARM_MODEL_MODEL_SIZES": "api/routers/config.py:505",
    "SWARM_MODULE_COHERENCE_GATE": "brain/nodes/__init__.py:2628",
    "SWARM_G1_RETRY_FUSE": "brain/nodes/__init__.py:validate_plan(R64-T3 同签名熔断泄压阀)",
    "SWARM_MODULE_LOCK_UPGRADE_WAIT_S": "brain/runner.py:760",
    "SWARM_MODEL_PROVIDERS": "api/routers/config.py:504",
    "SWARM_MODEL_ROUTING_COMPLEX": "api/_shared.py:42",
    "SWARM_MODEL_ROUTING_COMPLEX_FALLBACK": "api/_shared.py:43",
    "SWARM_MODEL_ROUTING_MEDIUM": "api/_shared.py:40",
    "SWARM_MODEL_ROUTING_MEDIUM_FALLBACK": "api/_shared.py:41",
    "SWARM_MODEL_ROUTING_MULTIMODAL": "api/_shared.py:44",
    "SWARM_MODEL_ROUTING_MULTIMODAL_FALLBACK": "api/_shared.py:45",
    "SWARM_MODEL_ROUTING_TRIVIAL": "api/_shared.py:38",
    "SWARM_MODEL_ROUTING_TRIVIAL_FALLBACK": "api/_shared.py:39",
    "SWARM_MODEL_SILICONFLOW_API_KEY": "api/_shared.py:23",
    "SWARM_MODEL_SILICONFLOW_BASE_URL": "api/_shared.py:24",
    "SWARM_MODEL_TIER": "brain/model_tier.py:12",
    "SWARM_MODEL_TIER_ENABLED": "brain/model_tier.py:110",
    "SWARM_MODEL_TIMEOUT_SECONDS": "config/settings.py:243",
    "SWARM_MODEL_WORKER_FALLBACK": "api/_shared.py:33",
    "SWARM_MODEL_WORKER_LOCAL": "api/_shared.py:32",
    "SWARM_MODEL_WORKER_PRIMARY": "api/_shared.py:31",
    "SWARM_MODEL_WORKER_STREAM_WALLCLOCK_S": "config/settings.py:278",
    "SWARM_MODEL_WORKER_TEMPERATURE": "api/_shared.py:35",
    "SWARM_NOTIFY_CHANNELS": "api/routers/config.py:236",
    "SWARM_NOTIFY_FORMAT": "api/notify.py:7",
    "SWARM_NOTIFY_WEBHOOK_URL": "api/notify.py:6",
    "SWARM_OBS_": "config/settings.py:656",
    "SWARM_PLAN_BATCH_BISECT": "brain/nodes/__init__.py:1186",
    "SWARM_PLAN_BATCH_CHUNK_GAP": "brain/nodes/__init__.py:464",
    "SWARM_PLAN_BATCH_MAX_ATTEMPTS": "brain/nodes/__init__.py:972",
    "SWARM_PLAN_BATCH_MAX_FILES": "brain/nodes/__init__.py:883",
    "SWARM_PLAN_BATCH_TIMEOUT": "brain/nodes/__init__.py:961",
    "SWARM_PLAN_INJECT_ENABLE": "api/routers/task.py:_plan_inject_enabled",  # R65D-T5 注入端总闸（默认关死）
    "SWARM_PLAN_BATCH_TIMEOUT_COOLDOWN": "brain/nodes/__init__.py:1209",
    "SWARM_PLAN_COMPLETENESS_RETRIES": "brain/nodes/__init__.py:2644",
    "SWARM_PLAN_COVERAGE_DESIGN": "brain/nodes/__init__.py:872",   # 既有债补登记
    "SWARM_PLAN_COVERAGE_GAP_MAX": "brain/nodes/__init__.py:2286",
    "SWARM_PLAN_COVERAGE_GAP_RATIO": "brain/nodes/__init__.py:2287",
    "SWARM_PLAN_COVERAGE_GATE": "brain/nodes/__init__.py:1185",
    "SWARM_PLAN_COVERAGE_TOPUP": "brain/nodes/__init__.py:1718",
    "SWARM_PLAN_SINGLE_TIMEOUT": "brain/nodes/__init__.py:1972",
    "SWARM_PLAN_SYMBOL_SURGERY": "brain/symbol_surgery.py:151",
    "SWARM_POOL_LIST_MAX_PAGES": "worker/sandbox_pool.py:508",
    "SWARM_PORT": "api/app.py:1929",
    "SWARM_PREPROCESS_TIMEOUT_SEC": "project/preprocess.py:28",
    "SWARM_PROVIDER_SLOT_WAIT_S": "models/router.py:356",
    "SWARM_QUOTE_COVER_MIN": "brain/requirements_extract.py:207",
    "SWARM_RESUME_SLOT_WAIT_S": "brain/scheduler.py:_slot_wait_cap_s",
    "SWARM_SCHEDULER_STOP_DRAIN_S": "brain/scheduler.py:_stop_drain_wait_s",
    "SWARM_QUOTE_MIN_TILE_CHARS": "brain/requirements_extract.py:206",
    "SWARM_RATELIMIT_DISABLED": "api/rate_limit.py:100",
    "SWARM_RATELIMIT_MAX_BUCKETS": "api/rate_limit.py:45",
    "SWARM_RBAC_ENABLED": "config/settings.py:860",
    "SWARM_RECONCILE_ACTIVE_GRACE_S": "brain/runner.py:1837",
    "SWARM_RECONCILE_INTERVAL_S": "api/app.py:1168",
    "SWARM_REDIS_ENABLED": "api/app.py:1460",
    "SWARM_REDIS_REPROBE_COOLDOWN_SEC": "infra/redis_client.py:70",
    "SWARM_REDIS_SOCKET_CONNECT_TIMEOUT_SEC": "infra/redis_client.py:39",
    "SWARM_REDIS_SOCKET_TIMEOUT_SEC": "infra/redis_client.py:47",
    "SWARM_REPLAN_CLAIM_DESC_SIM": "brain/nodes/__init__.py:1459",
    "SWARM_REQUIRE_PG_CHECKPOINTER": "brain/graph.py:826",
    "SWARM_REQUIRE_SECRET_KEY": "config/secret_store.py:92",
    "SWARM_RUNTIME_SMOKE_ENABLED": "brain/nodes/__init__.py:2432",
    "SWARM_RUNTIME_SMOKE_PLATEAU_STRICT": "brain/nodes/failure.py:185",
    "SWARM_RUNTIME_SMOKE_PREPARE_TIMEOUT_SEC": "brain/nodes/runtime_smoke.py:39",
    "SWARM_RUNTIME_SMOKE_TIMEOUT_SEC": "brain/nodes/runtime_smoke.py:37",
    "SWARM_SANDBOX_": "config/settings.py:444",
    "SWARM_WORKER_RUN_QUEUE_MAX": "worker/runner.py:_worker_run_queue_max",
    "SWARM_WORKER_RUN_RETENTION_S": "worker/runner.py:_worker_run_retention_s",
    "SWARM_WORKER_RUN_MAX_RETAINED": "worker/runner.py:_worker_run_max_retained",
    "SWARM_SANDBOX_API_KEY": "api/_shared.py:53",
    "SWARM_SANDBOX_API_URL": "api/_shared.py:50",
    "SWARM_SANDBOX_DEFAULT_TEMPLATE": "api/_shared.py:52",
    "SWARM_SANDBOX_MAX_SYNC_FILE_SIZE": "worker/executor_l1gate.py:261",
    "SWARM_SANDBOX_POOL_ENABLED": "worker/sandbox_pool.py:713",
    "SWARM_SANDBOX_PROXY_BASE": "api/_shared.py:51",
    "SWARM_SANDBOX_REQUEST_TIMEOUT": "worker/sandbox.py:730",
    "SWARM_SANDBOX_TAR_SYNC": "brain/nodes/verify.py:35",
    "SWARM_SANDBOX_ALLOW_LOCAL_FALLBACK": "config/settings.py:476",
    "SWARM_SANDBOX_USE_FOR_WORKER": "api/_shared.py:54",
    "SWARM_SANDBOX_VERIFY_SSL": "config/settings.py:458",
    "SWARM_SECRET_KEY": "api/routers/config.py:1109",
    "SWARM_SKILLS_": "config/settings.py:616",
    "SWARM_SKILLS_ADMIT_LLM_JUDGE": "config/settings.py:645",
    "SWARM_SKILLS_WORKER_PULL_ENABLED": "config/settings.py:663",
    "SWARM_SKILLS_DIR": "config/settings.py:922",
    "SWARM_SKILLS_ENABLED": "config/settings.py:619",
    "SWARM_SMOKE_LOGIN_": "brain/acceptance_spec.py:43",
    "SWARM_SMOKE_LOGIN_BODY_JSON": "brain/acceptance_spec.py:554",
    "SWARM_SMOKE_LOGIN_PATH": "brain/acceptance_spec.py:554",
    "SWARM_SMOKE_TOKEN": "brain/acceptance_spec.py:445",
    "SWARM_SMOKE_TOKEN_FIELD": "brain/acceptance_spec.py:558",
    "SWARM_SSE_MAX_SUBS_GLOBAL": "brain/runner.py:_GLOBAL_MAX_SUBS",
    "SWARM_SSE_MAX_SUBS_PER_TASK": "brain/runner.py:93",
    "SWARM_SSE_REAUTH_INTERVAL_S": "api/routers/task.py:55",
    "SWARM_SSE_SUB_QUEUE_MAX": "brain/runner.py:92",
    "SWARM_STAGING_URL": "brain/nodes/verify.py:400",
    "SWARM_STREAM_PROGRESS_HARD_MULT": "brain/nodes/__init__.py:489",
    "SWARM_SUBTASK_CONTEXT_BUDGET": "brain/planning_nodes.py:106",
    "SWARM_TASK_DEADLINE_PER_SUBTASK_S": "config/settings.py:762",
    "SWARM_TASK_DEADLINE_S": "config/settings.py:762",
    "SWARM_TASK_ID": "brain/l3_gitlab.py:247",
    "SWARM_TASK_LIST_DEFAULT_LIMIT": "api/routers/task.py:119",
    "SWARM_TOKEN_TTL_HOURS": "config/settings.py:743",
    "SWARM_TRANSIENT_DET_PLATEAU": "brain/nodes/failure.py:1853",   # 既有债补登记
    "SWARM_UPLOADS_GC_DAYS": "project/store.py:1223",
    "SWARM_CONTRACT_UNOWNED_RATIO": "brain/plan_validator.py:validate_contract_ownership",
    "SWARM_UPSTREAM_PRODUCTS_CAP": "brain/nodes/dispatch.py:120",
    "SWARM_UPLOAD_MAX_BODY_BYTES": "api/routers/upload.py:77",
    "SWARM_VALIDATE_PLAN_COMPLETENESS_GATE": "brain/nodes/__init__.py:2640",
    "SWARM_VALIDATE_PLAN_LLM_GATE": "brain/nodes/__init__.py:2574",
    "SWARM_VALIDATE_PLAN_SOFT_TIMEOUT": "brain/nodes/__init__.py:2618",
    "SWARM_WORKER_": "worker/executor.py:902",
    "SWARM_WORKER_BUILD_REPAIR_MAX_SECONDS": "worker/l1_pipeline.py:1223",
    "SWARM_WORKER_BUILD_REPAIR_ROUNDS": "worker/l1_pipeline.py:1211",
    "SWARM_WORKER_CLEAN_UPLOAD": "worker/executor_sync.py:623",
    "SWARM_WORKER_COMMAND_WHITELIST": "tools/build_tools.py:366",
    "SWARM_WORKER_CTX_KB_CHARS": "worker/prompts.py:259",
    "SWARM_WORKER_DEP_REPAIR": "worker/l1_pipeline.py:1155",
    "SWARM_SSH_STRICT_HOST_KEY": "worker/image_builder.py:SSHRunner.__enter__（=1 启用 RejectPolicy 严格主机公钥校验，需预置 known_hosts）",
    "SWARM_WORKER_DISPATCH_MODE": "infra/worker_dispatcher.py:92",
    "SWARM_WORKER_IMPORT_DRIFT_REPAIR": "worker/l1_pipeline.py:1041",
    "SWARM_WORKER_IMPORT_REPAIR": "worker/l1_pipeline.py:2764",
    "SWARM_WORKER_JVM_NS_FIX": "worker/executor_sync.py:864",
    "SWARM_WORKER_L1_FORMAT": "worker/l1_pipeline.py:2942",
    # R63-T9②：fix 轮 turn 连续性——上一产码轮对话（裁剪后）延续进修复轮，确定性
    # build 错回喂同一对话。CONTINUITY=false 回退旧行为（全新单消息轮）；
    # BUDGET_CHARS=携带预算（默认 24000，本地小窗 worker 可调小）。
    "SWARM_WORKER_FIX_TURN_CONTINUITY": "worker/executor_agent.py:_fix_carry_messages",
    "SWARM_WORKER_FIX_CARRY_BUDGET_CHARS": "worker/executor_agent.py:_fix_carry_messages",
    "SWARM_WORKER_L1_LINT": "worker/l1_pipeline.py:2956",
    "SWARM_WORKER_L1_LINT_GATE": "worker/l1_pipeline.py:2968",
    "SWARM_WORKER_L1_MAX_FILES": "worker/l1_pipeline.py:1202",
    "SWARM_WORKER_L1_SELF_REVIEW": "worker/l1_pipeline.py:3096",
    "SWARM_WORKER_RESET_SCOPE": "worker/executor_sync.py:410",
    "SWARM_WORKER_TDD_RED_GATE": "worker/executor_l1gate.py:311",
    "SWARM_WORKER_TRIVIAL_REPAIR": "worker/executor.py:1215",
    "SWARM_WORKER_TDD_RED_STRICT": "worker/executor.py:904",
    "SWARM_WORKER_VERIFY_AGENT_STEP": "worker/executor.py:679",
    "SWARM_WORKER_VERIFY_BAIL_FRACTION": "worker/executor.py:292",
    "SWARM_WORKSPACE_LIST_CAP": "worker/executor_sync.py:42",
    "SWARM_WORKSPACE_ROOT": "tools/paths.py:11",
}
